circuits.modpath("/button.lua")
circuits.modpath("/pressure_plate.lua")
circuits.modpath("/inverter.lua")
circuits.modpath("/entity_detector.lua")
circuits.modpath("/player_detector.lua")
circuits.modpath("/solar_panel.lua")